const regions = [
{region: 'Asia', abbreviation: 'asia'},
{region: 'Asia Pacific', abbreviation: 'asiapacific'},
{region: 'Australia', abbreviation: 'australia'},
{region: 'Australia Central', abbreviation: 'australiacentral'},
{region: 'Australia Central 2', abbreviation: 'australiacentral2'},
{region: 'Australia East', abbreviation: 'australiaeast'},
{region: 'Australia Southeast', abbreviation: 'australiasoutheast'},
{region: 'Brazil', abbreviation: 'brazil'},
{region: 'Brazil South', abbreviation: 'brazilsouth'},
{region: 'Brazil Southeast', abbreviation: 'brazilsoutheast'},
{region: 'Canada', abbreviation: 'canada'},
{region: 'Canada Central', abbreviation: 'canadacentral'},
{region: 'Canada East', abbreviation: 'canadaeast'},
{region: 'Central India', abbreviation: 'centralindia'},
{region: 'Central US', abbreviation: 'centralus'},
{region: 'Central US EUAP', abbreviation: 'centraluseuap'},
{region: 'Central US (Stage)', abbreviation: 'centralusstage'},
{region: 'East Asia', abbreviation: 'eastasia'},
{region: 'East Asia (Stage)', abbreviation: 'eastasiastage'},
{region: 'East US', abbreviation: 'eastus'},
{region: 'East US 2', abbreviation: 'eastus2'},
{region: 'East US 2 EUAP', abbreviation: 'eastus2euap'},
{region: 'East US 2 (Stage)', abbreviation: 'eastus2stage'},
{region: 'East US (Stage)', abbreviation: 'eastusstage'},
{region: 'Europe', abbreviation: 'europe'},
{region: 'France', abbreviation: 'france'},
{region: 'France Central', abbreviation: 'francecentral'},
{region: 'France South', abbreviation: 'francesouth'},
{region: 'Germany', abbreviation: 'germany'},
{region: 'Germany North', abbreviation: 'germanynorth'},
{region: 'Germany West Central', abbreviation: 'germanywestcentral'},
{region: 'Global', abbreviation: 'global'},
{region: 'India', abbreviation: 'india'},
{region: 'Japan', abbreviation: 'japan'},
{region: 'Japan East', abbreviation: 'japaneast'},
{region: 'Japan West', abbreviation: 'japanwest'},
{region: 'Jio India Central', abbreviation: 'jioindiacentral'},
{region: 'Jio India West', abbreviation: 'jioindiawest'},
{region: 'Korea', abbreviation: 'korea'},
{region: 'Korea Central', abbreviation: 'koreacentral'},
{region: 'Korea South', abbreviation: 'koreasouth'},
{region: 'North Central US', abbreviation: 'northcentralus'},
{region: 'North Central US (Stage)', abbreviation: 'northcentralusstage'},
{region: 'North Europe', abbreviation: 'ne'},
{region: 'Norway', abbreviation: 'norway'},
{region: 'Norway East', abbreviation: 'norwayeast'},
{region: 'Norway West', abbreviation: 'norwaywest'},
{region: 'South Africa', abbreviation: 'southafrica'},
{region: 'South Africa North', abbreviation: 'southafricanorth'},
{region: 'South Africa West', abbreviation: 'southafricawest'},
{region: 'South Central US', abbreviation: 'southcentralus'},
{region: 'South Central US (Stage)', abbreviation: 'southcentralusstage'},
{region: 'Southeast Asia', abbreviation: 'southeastasia'},
{region: 'Southeast Asia (Stage)', abbreviation: 'southeastasiastage'},
{region: 'South India', abbreviation: 'southindia'},
{region: 'Sweden Central', abbreviation: 'swedencentral'},
{region: 'Switzerland', abbreviation: 'switzerland'},
{region: 'Switzerland North', abbreviation: 'switzerlandnorth'},
{region: 'Switzerland West', abbreviation: 'switzerlandwest'},
{region: 'United Arab Emirates', abbreviation: 'uae'},
{region: 'UAE Central', abbreviation: 'uaecentral'},
{region: 'UAE North', abbreviation: 'uaenorth'},
{region: 'United Kingdom', abbreviation: 'uk'},
{region: 'UK South', abbreviation: 'uksouth'},
{region: 'UK West', abbreviation: 'ukwest'},
{region: 'United States', abbreviation: 'unitedstates'},
{region: 'United States EUAP', abbreviation: 'unitedstateseuap'},
{region: 'West Central US', abbreviation: 'westcentralus'},
{region: 'West Europe', abbreviation: 'westeurope'},
{region: 'West India', abbreviation: 'westindia'},
{region: 'West US', abbreviation: 'westus'},
{region: 'West US 2', abbreviation: 'westus2'},
{region: 'West US 2 (Stage)', abbreviation: 'westus2stage'},
{region: 'West US 3', abbreviation: 'westus3'},
{region: 'West US (Stage)', abbreviation: 'westus3'}

]

export default regions